// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTB77ZMlxM0PjylY2NHf-bBhdKiSaTqCI',
    appId: '1:702825180785:web:59dfe9a8b01dfbd176f5d0',
    messagingSenderId: '702825180785',
    projectId: 'alu-hub-2a873',
    authDomain: 'alu-hub-2a873.firebaseapp.com',
    storageBucket: 'alu-hub-2a873.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUD8LVYuncniE5YIkjTh2IshOdGSpUK9k',
    appId: '1:702825180785:android:64bbf2336233787b76f5d0',
    messagingSenderId: '702825180785',
    projectId: 'alu-hub-2a873',
    storageBucket: 'alu-hub-2a873.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABBBjdwWwcWSU9YJDIB_rhB5eGcDegfvE',
    appId: '1:702825180785:ios:203e0fead5a630d976f5d0',
    messagingSenderId: '702825180785',
    projectId: 'alu-hub-2a873',
    storageBucket: 'alu-hub-2a873.firebasestorage.app',
    iosBundleId: 'com.aluhub.aluHub',
  );
}
